/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package northlondontradecompanies.ui;

import javax.swing.JOptionPane;
import northlondontradecompanies.core.Administrator;
import northlondontradecompanies.core.Company;
import northlondontradecompanies.core.ValidationException;

/**
 * This class enables user with the GUI to add, remove or change a <code>Company</code>
 * detail. It is also used to setup logic for if the user should be adding a
 * new company or editing an existing one.
 *
 *
 * @author tdx_429
 */
public class CompanyEditor extends javax.swing.JPanel {

    /**
     * Instance variable to reference a Company object
     */
    private Company company;

    /**
     * The constructor sets the editor to be in "add" mode by default when first
     * instantiated.
     */
    public CompanyEditor() {
        initComponents();
        clearCompany();
    }

    /**
     * Method used to clear the field of the panel. Supposing , an user wants to
     * add an new entry, the company instance variable is set to null, and each
     * of the text entry fields is emptied, and a <I>modeLabel</I> is set to
     * inform the user that they are adding a new company.
     *
     */
    void clearCompany() {
        company = null;
        nameField.setText("");
        locationField.setText("");
        servicesField.setText("");
        numberOfEmployeesField.setText("");
        dailyRateField.setText("");
        generalDescriptionField.setText("");
        modeLabel.setText("Add New Company");
        messageLabel.setText("");

    }

    /**
     * Method that set the text entry fields with the existing values retrieved
     * from the supplied company. The modeLabel is set to inform the user that
     * they are changing an existing company
     *
     * @param company the company that needs to be edited
     */
    void setCompany(Company company) {
        this.company = company;
        nameField.setText(company.getName());
        locationField.setText(company.getLocation());
        servicesField.setText(company.getServices());
        numberOfEmployeesField.setText(company.getNumberOfEmployees().toPlainString());
        dailyRateField.setText(company.getDailyRate().toPlainString());
        generalDescriptionField.setText(company.getGeneralDescription());
        messageLabel.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        modeLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        locationLabel = new javax.swing.JLabel();
        servicesLabel = new javax.swing.JLabel();
        numberOfEmployeesLabel = new javax.swing.JLabel();
        dailyRateLabel = new javax.swing.JLabel();
        generalDescriptionLabel = new javax.swing.JLabel();
        SaveButton = new javax.swing.JButton();
        messageLabel = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        locationField = new javax.swing.JTextField();
        servicesField = new javax.swing.JTextField();
        numberOfEmployeesField = new javax.swing.JTextField();
        dailyRateField = new javax.swing.JTextField();
        generalDescriptionField = new javax.swing.JTextField();

        modeLabel.setText("Mode will go here");

        nameLabel.setText("Name:");

        locationLabel.setText("Location:");

        servicesLabel.setText("Services:");

        numberOfEmployeesLabel.setText(" Employees Number:");

        dailyRateLabel.setText("Daily Rate:");

        generalDescriptionLabel.setText("General Description");

        SaveButton.setText("Save");
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });

        messageLabel.setText("Message will go here");

        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });

        locationField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locationFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(locationLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nameLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dailyRateLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(servicesLabel, javax.swing.GroupLayout.Alignment.LEADING))
                                .addContainerGap(439, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(generalDescriptionLabel)
                                .addContainerGap(399, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(numberOfEmployeesLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(generalDescriptionField, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(dailyRateField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
                                .addComponent(numberOfEmployeesField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(servicesField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(locationField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(SaveButton, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(modeLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(messageLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nameField, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(modeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(locationField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(servicesLabel)
                            .addComponent(servicesField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numberOfEmployeesLabel)
                            .addComponent(numberOfEmployeesField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dailyRateLabel)
                            .addComponent(dailyRateField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(generalDescriptionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(generalDescriptionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(SaveButton))
                    .addComponent(locationLabel))
                .addGap(18, 18, 18)
                .addComponent(messageLabel)
                .addGap(84, 84, 84))
        );
    }// </editor-fold>//GEN-END:initComponents
    /**
     * The method is executed whenever the Save button is clicked by the user to
     * either add a new Company or change an existing one. A reference to the
     * Administrator singleton object is firstly obtained, to invoke either of
     * its createCompany() or changeCompany() method. The method checks that if
     * the company instance variable is null or not, in order to decide whether
     * the company is being added or changed. If the company is set to null , it
     * will add the the company by invoking createCompany() method, else it will
     * invoke the changeCompany method for suffice action required. The call to
     * clearCompany() is also added after the user adds a new company, to be
     * ready to add a new one.
     *
     * Note: Because the createZookeeper() method can potentially throw a
     * checked exception , the statement are enclosed within a try ...catch
     * block. If an exception is thrown, the JOptionPane class is used to inform
     * the user of the problem.
     *
     *
     */
    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
        // TODO add your handling code here:

        Administrator admin = Administrator.getInstance();
        try {
            if (company == null) {
                admin.createCompany(nameField.getText(), locationField.getText(), servicesField.getText(), numberOfEmployeesField.getText(), dailyRateField.getText(), generalDescriptionField.getText());
                messageLabel.setText("New Company Added");
                clearCompany();
            } else {
                admin.changeCompany(company, nameField.getText(), locationField.getText(), servicesField.getText(), numberOfEmployeesField.getText(), dailyRateField.getText(), generalDescriptionField.getText());
                messageLabel.setText("Company details changed");
            }
        } catch (ValidationException ex) {

            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_SaveButtonActionPerformed

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFieldActionPerformed

    private void locationFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locationFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_locationFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SaveButton;
    private javax.swing.JTextField dailyRateField;
    private javax.swing.JLabel dailyRateLabel;
    private javax.swing.JTextField generalDescriptionField;
    private javax.swing.JLabel generalDescriptionLabel;
    private javax.swing.JTextField locationField;
    private javax.swing.JLabel locationLabel;
    private javax.swing.JLabel messageLabel;
    private javax.swing.JLabel modeLabel;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField numberOfEmployeesField;
    private javax.swing.JLabel numberOfEmployeesLabel;
    private javax.swing.JTextField servicesField;
    private javax.swing.JLabel servicesLabel;
    // End of variables declaration//GEN-END:variables
}
